name: Build, Push and Deploy to ECS

on:
  push:
    branches:
      - feature1

jobs:
  build-and-push:
    name: Build and Push
    runs-on: ubuntu-22.04
    outputs:
      image: ${{ steps.build-image.outputs.image }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push Docker image
        id: build-image
        env:
          IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
        run: |
          docker build -t "${IMAGE_NAME}" .
          docker push "${IMAGE_NAME}"

            # deploy-to-ecs:
            #   name: Deploy to ECS
            #   needs: build-and-push
            #   runs-on: ubuntu-22.04
            #   steps:
            #     - name: Configure AWS credentials
            #       uses: aws-actions/configure-aws-credentials@v1
            #       with:
            #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            #         aws-region: ${{ secrets.AWS_REGION }}

            #     - name: Deploy to ECS
            #       env:
            #         AWS_REGION: ${{ secrets.AWS_REGION }}
            #         CLUSTER_NAME: ${{ secrets.ECS_CLUSTER_NAME }}
            #         SERVICE_NAME: ${{ secrets.ECS_SERVICE_NAME }}
            #         TASK_DEFINITION: ${{ secrets.ECS_TASK_DEFINITION }}
            #         CONTAINER_NAME: ${{ secrets.ECS_CONTAINER_NAME }}
            #         IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
            #       run: |
            #         aws ecs update-service --cluster $CLUSTER_NAME --service $SERVICE_NAME --force-new-deployment

