name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - feature1

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Validate Environment Variables
        run: |
          if [ -z "${{ secrets.ECR_REPO_NAME }}" ]; then
            echo "ECR_REPO_NAME is not set!"
            exit 1
          fi
          if [ -z "${{ secrets.AWS_ACCOUNT_ID }}" ]; then
            echo "AWS_ACCOUNT_ID is not set!"
            exit 1
          fi
          if [ -z "${{ secrets.AWS_REGION }}" ]; then
            echo "AWS_REGION is not set!"
            exit 1
          fi

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push Docker image
        env:
          ECR_REPO_NAME: ${{ secrets.ECR_REPO_NAME }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        run: |
          docker build -t $ECR_REPO_NAME:latest .
          docker tag $ECR_REPO_NAME:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME:latest
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME:latest
